"""empty message

Revision ID: 975425d4821f
Revises: e36f1d0c4947
Create Date: 2019-06-26 16:09:27.950596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '975425d4821f'
down_revision = 'e36f1d0c4947'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('validator_role_requests',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('requester_user_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('reviewed_howto', sa.Boolean(), nullable=True),
    sa.Column('read_learnosm', sa.Boolean(), nullable=True),
    sa.Column('read_code_conduct', sa.Boolean(), nullable=True),
    sa.Column('agreed_interactions', sa.Boolean(), nullable=True),
    sa.Column('agreed_osmdata', sa.Boolean(), nullable=True),
    sa.Column('response_user_id', sa.BigInteger(), nullable=True),
    sa.Column('response_reason', sa.String(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['requester_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['response_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validator_role_requests_id'), 'validator_role_requests', ['id'], unique=False)
    op.drop_index('idx_task_validation_mapper_status_composite', table_name='task_invalidation_history')
    op.create_index('idx_task_validation_mapper_status_composite', 'task_invalidation_history', ['invalidator_id', 'is_closed'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_task_validation_mapper_status_composite', table_name='task_invalidation_history')
    op.create_index('idx_task_validation_mapper_status_composite', 'task_invalidation_history', ['mapper_id', 'is_closed'], unique=False)
    op.drop_index(op.f('ix_validator_role_requests_id'), table_name='validator_role_requests')
    op.drop_table('validator_role_requests')
    # ### end Alembic commands ###
